apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ashpamongodb
  namespace: mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: deploymongodb
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60