apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongo
spec:
  selector:
    app: deploymongodb
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-svc
  namespace: mongo
spec:
  selector:
    app: deploymongoexpress
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081