apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: mongo
data:
  # Credentials for the user with root role. This user is used for replicasets to communicate with each other and for admin related cmds. Don't use this user to connect from outside the cluster.
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  # Credentials for the secondary user with dbAdmin role. This user can be used for all CRUD operations and is used for mongo-express to connect to MongoDB.
  DB_USERNAME: dXNlcjE=
  DB_PASSWORD: dXNlcjE=