apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: mongo
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  DB_USERNAME: dXNlcjE=
  DB_PASSWORD: dXNlcjE=